#!/usr/bin/env bash
#I'll need to use the remainder functions to find multiples of number. If it comes back as zero, echo the word
x=1
while [ $x -le 99 ]
do
	if (( x % 3 == 0 )) && (( x % 5 == 0 ))
	then 
		echo "FizzBuzz"
	((x++))
fi
	if (( x % 3 == 0 )) && [ $(( x % 5 )) -ne 0 ]
	then
		echo "Fizz"
	((x++))
fi
	if (( x % 5 == 0 )) && [ $(( x % 3 )) -ne 0 ]
	then
		echo "Buzz"
	((x++))
fi
	if [ $x -gt 100 ]
	then
		break
	else
	echo "$x"
	((x++))
fi
done
