#!/usr/bin/env bash
# 20 times where certian numbers are followed by a statement
x=1
while [ $x -le 19 ]
do
	x=$((x+1))
	echo "$x"
case "$x" in
	"4") echo "bad luck from China"
;;
	"9") echo "bad luck from Japan"
;;
	"17") echo "bad luck from Italy"
;;
esac
done
