#!/usr/bin/env bash
#Script that gives info about the school files
if [ -e school ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [ -s school ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f school ]
then
	echo "school is a regular file"
else 
	:
fi
